name: CI
on: [push]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ECHO_TOKEN }}
    - name: Repo 1
      run: |
        echo "31" > Sample-Repo/echo.txt
        
    - name: Repo 2
      run: |
        echo "31" > Another-Sample-Repo/echo.txt
     
    - name: Check for modified files
      id: git-check
      run: | 
        git diff --name-only | xargs -L1 dirname | uniq > changes.txt
        #echo $(wc -l changes.txt)
        while read p; do          
          if [ $p != "." ]
          then
            echo ${p}
            voice="New release for $p"
            echo $voice
            msg=' {"notification":"Hello World!","accessCode":"${{ secrets.ECHO_KEY }}"} '            
            jq --arg prefix "$voice" '
            .notification |= map_values($prefix + .)
            ' msg
            #jq '.notification = $newVal' --arg newVal $voice <<<"$msg"
            echo $msg
            #curl https://api.notifymyecho.com/v1/NotifyMe -H "Content-Type: application/json" -d $msg
          fi
        done <changes.txt        
        echo "" > changes.txt
      
    - name: Commit latest release version
      run: |
        git config --global user.name 'QAInsights'
        git config --global user.email 'catch.nkn@gmail.com'
        git commit -am "New release version"
        git push
