# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ECHO_TOKEN }}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl -sL https://api.github.com/repos/QAInsights/Echo-The-Release/releases/latest | \
        jq -r ".tag_name" > release-versions/echo.txt
        cat release-versions/echo.txt
    - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'QAInsights'
          git config --global user.email 'catch.nkn@gmail.com'
          git commit -am "New release version"
          git push
        
