name: CI
on: [push]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ECHO_TOKEN }}
    - name: Repo 1
      run: |
        echo "2" > Sample-Repo/echo.txt
        
    - name: Repo 2
      run: |
        echo "2" > Another-Sample-Repo/echo.txt
     
    - name: Check for modified files
      id: git-check
      run: | 
        git status --porcelain
      
    - name: Commit latest release version
      run: |
        git config --global user.name 'QAInsights'
        git config --global user.email 'catch.nkn@gmail.com'
        git commit -am "New release version"
        git push
